@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MmFmYjYxLWUyMTktNGRkOS05YTlhLTFmMWQ3YTEyNDg1ZSIsImlhdCI6MTcxNDE3NDU2OCwiZXhwIjoxNzE0MjYwOTY4fQ.9u5TLo9dKpyJRZuTjHA4etzcf4DOjbXY1DrCyaW-2D4
@BASE_URL=http://localhost:3000


### Get all ruangan
GET {{BASE_URL}}/ruangan
Authorization: Bearer {{TOKEN}}
Accept: application/json


